# Generated by Django 4.2.3 on 2023-07-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['post_date']},
        ),
    ]
